/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createjavavariabledeclarations;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author dev2
 */
public class GUI extends javax.swing.JFrame
{

    public static final String PACKAGE_ACCESS_STRING = "package (default)";
    public static final String USE_EXACTLY_STRING = "Use this exactly";
    public static final String INCREMENT_AND_APPEND_STRING = "Increment and append an ID to each";

    public static final String[] types =
    {
        "String", "int", "double", "long", "boolean", "short", "float", "char", "Object",
    };

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();
        for (int i = 0; i < types.length; i++)
        {
            typeCombo.addItem(types[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        accessModifiersCombo = new javax.swing.JComboBox();
        finalCheck = new javax.swing.JCheckBox();
        staticCheck = new javax.swing.JCheckBox();
        typeCombo = new javax.swing.JComboBox();
        nameT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        generateB = new javax.swing.JButton();
        howToUseNameCombo = new javax.swing.JComboBox();
        addSemiColonCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generate Java Variable Names");
        setLocationByPlatform(true);

        jLabel1.setText("Java variable declaration generator");

        accessModifiersCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "private", "public", "package (default)", "protected" }));

        finalCheck.setText("final");

        staticCheck.setText("static");

        jLabel2.setText("Name/Name starts with");

        jLabel3.setText("Number to declare:");

        numberT.setText("1");

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane1.setViewportView(outputTA);

        generateB.setText("Generate");
        generateB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generateBActionPerformed(evt);
            }
        });

        howToUseNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Use this exactly", "Increment and append an ID to each" }));
        howToUseNameCombo.setToolTipText("This applies if you are generating more than one variable.");

        addSemiColonCheck.setText("End with ;");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(numberT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(accessModifiersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(finalCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(staticCheck)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(generateB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(howToUseNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addSemiColonCheck)))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessModifiersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalCheck)
                    .addComponent(staticCheck)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howToUseNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSemiColonCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(accessModifiersCombo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(finalCheck, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(staticCheck, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(typeCombo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(nameT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(numberT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(generateB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(howToUseNameCombo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addSemiColonCheck, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generateBActionPerformed
    {//GEN-HEADEREND:event_generateBActionPerformed
        String variableDecl = "";
        boolean useExactly = true;
        int numberToGen = 1;
        String output = "";
        boolean addSemiColon = addSemiColonCheck.isSelected();

        if (!((String) accessModifiersCombo.getSelectedItem()).equals(PACKAGE_ACCESS_STRING))
        {
            variableDecl += ((String) accessModifiersCombo.getSelectedItem());
        }

        if (finalCheck.isSelected())
        {
            variableDecl += " " + finalCheck.getText();
        }

        if (staticCheck.isSelected())
        {
            variableDecl += " " + staticCheck.getText();
        }

        variableDecl += " " + (String) typeCombo.getSelectedItem();
        variableDecl += " " + nameT.getText();

        if (((String) howToUseNameCombo.getSelectedItem()).equals(INCREMENT_AND_APPEND_STRING))
        {
            useExactly = false;
        }

        try
        {
            numberToGen = Integer.parseInt(numberT.getText());
        } catch (NumberFormatException ex)
        {
            numberT.setText("That input is invalid.");
            numberToGen = 1;
        }

        for (int i = 0; i < numberToGen; i++)
        {
            if (useExactly)
            {
                output += variableDecl + (addSemiColon ? "" : ";") + "\n";
            } else
            {
                output += variableDecl + i + (addSemiColon ? "" : ";") + "\n";
            }
        }

        if (addSemiColonCheck.isSelected())
        {
            for (int i = 0; i < 10; i++)
            {

            }
        }

        outputTA.setText(output);

    }//GEN-LAST:event_generateBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
        {
            System.out.println("Problem setting look and feel.");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accessModifiersCombo;
    private javax.swing.JCheckBox addSemiColonCheck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox finalCheck;
    private javax.swing.JButton generateB;
    private javax.swing.JComboBox howToUseNameCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameT;
    private javax.swing.JTextField numberT;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JCheckBox staticCheck;
    private javax.swing.JComboBox typeCombo;
    // End of variables declaration//GEN-END:variables
}
